name: Build

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/build.yaml
      - cmd/**
      - internal/**
      - go.*
  push:
    branches:
      - main
    paths:
      - .github/workflows/build.yaml
      - cmd/**
      - internal/**
      - go.*

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: go test -short -v ./...

  build-bot:
    name: Build bot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build bot
        run: go build -o bot cmd/bot/*.go

  build-ytplay:
    name: Build ytplay
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build ytplay
        run: go build -o ytplay cmd/ytplay/*.go
